In [2]:
import torch

In [3]:
# Создайте случайный FloatTensor размера 3x4x5
a = torch.rand(3,4,5).type(torch.FloatTensor)
a

tensor([[[0.2674, 0.6832, 0.4773, 0.9905, 0.2500],
         [0.0480, 0.2752, 0.0332, 0.6656, 0.4119],
         [0.2298, 0.9726, 0.2719, 0.1452, 0.6696],
         [0.6764, 0.6592, 0.8936, 0.3219, 0.2681]],

        [[0.7901, 0.5873, 0.3897, 0.0885, 0.7532],
         [0.2284, 0.4738, 0.9440, 0.0497, 0.4222],
         [0.0441, 0.4760, 0.7208, 0.3126, 0.0190],
         [0.5029, 0.2132, 0.1101, 0.9263, 0.1243]],

        [[0.6439, 0.2239, 0.0956, 0.1881, 0.3190],
         [0.3876, 0.0524, 0.2019, 0.0897, 0.1771],
         [0.9590, 0.1238, 0.5914, 0.5050, 0.7113],
         [0.1938, 0.6916, 0.4995, 0.6374, 0.1594]]])

In [4]:
# Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [5]:
# Приведите его к форме 6 X 10
c = a.reshape(6, 10)
c

tensor([[0.2674, 0.6832, 0.4773, 0.9905, 0.2500, 0.0480, 0.2752, 0.0332, 0.6656,
         0.4119],
        [0.2298, 0.9726, 0.2719, 0.1452, 0.6696, 0.6764, 0.6592, 0.8936, 0.3219,
         0.2681],
        [0.7901, 0.5873, 0.3897, 0.0885, 0.7532, 0.2284, 0.4738, 0.9440, 0.0497,
         0.4222],
        [0.0441, 0.4760, 0.7208, 0.3126, 0.0190, 0.5029, 0.2132, 0.1101, 0.9263,
         0.1243],
        [0.6439, 0.2239, 0.0956, 0.1881, 0.3190, 0.3876, 0.0524, 0.2019, 0.0897,
         0.1771],
        [0.9590, 0.1238, 0.5914, 0.5050, 0.7113, 0.1938, 0.6916, 0.4995, 0.6374,
         0.1594]])

In [6]:
c.shape

torch.Size([6, 10])

In [24]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
b = torch.FloatTensor([1, 4, 2, 2, 1])
c.T @ b.repeat(6, 2)



tensor([[ 2.9343, 11.7373,  5.8687,  5.8687,  2.9343,  2.9343, 11.7373,  5.8687,
          5.8687,  2.9343],
        [ 3.0666, 12.2665,  6.1333,  6.1333,  3.0666,  3.0666, 12.2665,  6.1333,
          6.1333,  3.0666],
        [ 2.5466, 10.1864,  5.0932,  5.0932,  2.5466,  2.5466, 10.1864,  5.0932,
          5.0932,  2.5466],
        [ 2.2299,  8.9195,  4.4598,  4.4598,  2.2299,  2.2299,  8.9195,  4.4598,
          4.4598,  2.2299],
        [ 2.7221, 10.8886,  5.4443,  5.4443,  2.7221,  2.7221, 10.8886,  5.4443,
          5.4443,  2.7221],
        [ 2.0371,  8.1486,  4.0743,  4.0743,  2.0371,  2.0371,  8.1486,  4.0743,
          4.0743,  2.0371],
        [ 2.3655,  9.4620,  4.7310,  4.7310,  2.3655,  2.3655,  9.4620,  4.7310,
          4.7310,  2.3655],
        [ 2.6823, 10.7290,  5.3645,  5.3645,  2.6823,  2.6823, 10.7290,  5.3645,
          5.3645,  2.6823],
        [ 2.6906, 10.7622,  5.3811,  5.3811,  2.6906,  2.6906, 10.7622,  5.3811,
          5.3811,  2.6906],
        [ 1.5631,  

In [65]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
print(a)
# torch.reshape(a, (6, 10))
d = a.view(6, 10)
print(d.shape)
e = torch.matmul(d, d.T).size()
print(e)

tensor([[[0.2674, 0.6832, 0.4773, 0.9905, 0.2500],
         [0.0480, 0.2752, 0.0332, 0.6656, 0.4119],
         [0.2298, 0.9726, 0.2719, 0.1452, 0.6696],
         [0.6764, 0.6592, 0.8936, 0.3219, 0.2681]],

        [[0.7901, 0.5873, 0.3897, 0.0885, 0.7532],
         [0.2284, 0.4738, 0.9440, 0.0497, 0.4222],
         [0.0441, 0.4760, 0.7208, 0.3126, 0.0190],
         [0.5029, 0.2132, 0.1101, 0.9263, 0.1243]],

        [[0.6439, 0.2239, 0.0956, 0.1881, 0.3190],
         [0.3876, 0.0524, 0.2019, 0.0897, 0.1771],
         [0.9590, 0.1238, 0.5914, 0.5050, 0.7113],
         [0.1938, 0.6916, 0.4995, 0.6374, 0.1594]]])
torch.Size([6, 10])
torch.Size([6, 6])


In [ ]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)


In [72]:
# Создайте единичный тензор размера 5x6
j = torch.normal(mean=torch.zeros(5,6))
j

tensor([[-0.1643, -0.0426,  1.1135,  0.8877, -0.2154,  0.3540],
        [-2.5347,  0.4340,  1.5184, -0.0883,  0.6461,  0.0196],
        [-0.3773, -1.0183, -0.7993,  0.3155,  0.6497,  0.9821],
        [ 0.8922, -1.5841,  1.1827, -0.7682, -0.6746, -0.5824],
        [-0.1079, -1.0866,  2.3333, -0.7665,  1.3482,  0.5948]])

In [73]:
# Переведите его в формат numpy
j.numpy()

array([[-0.16426767, -0.0426389 ,  1.1135082 ,  0.88769597, -0.21540311,
         0.3539903 ],
       [-2.5346549 ,  0.43396777,  1.5183897 , -0.0883396 ,  0.64605343,
         0.01962131],
       [-0.37726536, -1.0183371 , -0.7992761 ,  0.31551594,  0.6497002 ,
         0.9820593 ],
       [ 0.8921666 , -1.584087  ,  1.1827129 , -0.7682138 , -0.6746322 ,
        -0.5823981 ],
       [-0.1078831 , -1.086629  ,  2.3332603 , -0.7665244 ,  1.3481696 ,
         0.59476465]], dtype=float32)

In [ ]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 